export interface CivicExtended {
  building: string;
  floor: string;
  room: string;
  placeType: string;
  name: string;
  landmark: string;
}

export interface Location {
  streetNumber: string;
  streetName: string;
  streetSuffix: string;
  city: string;
  county: string;
  postalCode: string;
  latitude: number;
  longitude: number;
  extended: CivicExtended;
}

export const LOCATIONS: Location[] = [
  {
    streetNumber: "1",
    streetName: "Apple Park",
    streetSuffix: "Way",
    city: "Cupertino",
    county: "Santa Clara",
    postalCode: "95014",
    latitude: 37.3349,
    longitude: -122.0090,
    extended: {
      building: "Apple Park Main Building",
      floor: "2",
      room: "N2-200",
      placeType: "office",
      name: "Apple Inc.",
      landmark: "Apple Park",
    },
  },
  {
    streetNumber: "1600",
    streetName: "Amphitheatre",
    streetSuffix: "Pkwy",
    city: "Mountain View",
    county: "Santa Clara",
    postalCode: "94043",
    latitude: 37.4220,
    longitude: -122.0841,
    extended: {
      building: "Building 43",
      floor: "3",
      room: "3-G42",
      placeType: "office",
      name: "Google LLC",
      landmark: "Googleplex",
    },
  },
  {
    streetNumber: "415",
    streetName: "Mission",
    streetSuffix: "St",
    city: "San Francisco",
    county: "San Francisco",
    postalCode: "94105",
    latitude: 37.7898,
    longitude: -122.3973,
    extended: {
      building: "Salesforce Tower",
      floor: "61",
      room: "6100",
      placeType: "office",
      name: "Salesforce",
      landmark: "Salesforce Tower",
    },
  },
  {
    streetNumber: "1200",
    streetName: "Park",
    streetSuffix: "Ave",
    city: "Emeryville",
    county: "Alameda",
    postalCode: "94608",
    latitude: 37.8330,
    longitude: -122.2900,
    extended: {
      building: "Steve Jobs Building",
      floor: "2",
      room: "200",
      placeType: "office",
      name: "Pixar Animation Studios",
      landmark: "Pixar HQ",
    },
  },
  {
    streetNumber: "45500",
    streetName: "Fremont",
    streetSuffix: "Blvd",
    city: "Fremont",
    county: "Alameda",
    postalCode: "94538",
    latitude: 37.4937,
    longitude: -121.9446,
    extended: {
      building: "Tesla Factory",
      floor: "1",
      room: "A1",
      placeType: "industrial",
      name: "Tesla, Inc.",
      landmark: "Tesla Fremont Factory",
    },
  },
  {
    streetNumber: "39",
    streetName: "Pier",
    streetSuffix: "",
    city: "San Francisco",
    county: "San Francisco",
    postalCode: "94133",
    latitude: 37.8087,
    longitude: -122.4098,
    extended: {
      building: "Pier 39 Main Building",
      floor: "1",
      room: "A1",
      placeType: "commercial",
      name: "Pier 39",
      landmark: "Pier 39",
    },
  },
  {
    streetNumber: "1",
    streetName: "Ferry Building",
    streetSuffix: "",
    city: "San Francisco",
    county: "San Francisco",
    postalCode: "94111",
    latitude: 37.7956,
    longitude: -122.3933,
    extended: {
      building: "Ferry Building Marketplace",
      floor: "1",
      room: "42",
      placeType: "commercial",
      name: "Ferry Building",
      landmark: "Ferry Building",
    },
  },
  {
    streetNumber: "1",
    streetName: "Telegraph Hill",
    streetSuffix: "Blvd",
    city: "San Francisco",
    county: "San Francisco",
    postalCode: "94133",
    latitude: 37.8024,
    longitude: -122.4058,
    extended: {
      building: "Coit Tower",
      floor: "1",
      room: "Observation",
      placeType: "public",
      name: "Coit Tower",
      landmark: "Coit Tower",
    },
  },
  {
    streetNumber: "151",
    streetName: "Third",
    streetSuffix: "St",
    city: "San Francisco",
    county: "San Francisco",
    postalCode: "94103",
    latitude: 37.7857,
    longitude: -122.4011,
    extended: {
      building: "SFMOMA Building",
      floor: "2",
      room: "2A",
      placeType: "public",
      name: "SFMOMA",
      landmark: "SFMOMA",
    },
  },
  {
    streetNumber: "3601",
    streetName: "Lyon",
    streetSuffix: "St",
    city: "San Francisco",
    county: "San Francisco",
    postalCode: "94123",
    latitude: 37.8029,
    longitude: -122.4484,
    extended: {
      building: "Palace of Fine Arts",
      floor: "1",
      room: "Main Hall",
      placeType: "public",
      name: "Palace of Fine Arts",
      landmark: "Palace of Fine Arts",
    },
  },
  {
    streetNumber: "100",
    streetName: "Campanile",
    streetSuffix: "Way",
    city: "Berkeley",
    county: "Alameda",
    postalCode: "94720",
    latitude: 37.8721,
    longitude: -122.2578,
    extended: {
      building: "Sather Tower",
      floor: "10",
      room: "Observation Deck",
      placeType: "public",
      name: "UC Berkeley Campanile",
      landmark: "UC Berkeley",
    },
  },
  {
    streetNumber: "450",
    streetName: "Jane Stanford",
    streetSuffix: "Way",
    city: "Stanford",
    county: "Santa Clara",
    postalCode: "94305",
    latitude: 37.4275,
    longitude: -122.1697,
    extended: {
      building: "Memorial Church",
      floor: "1",
      room: "Nave",
      placeType: "public",
      name: "Stanford Memorial Church",
      landmark: "Stanford Quad",
    },
  },
  {
    streetNumber: "4900",
    streetName: "Marie P DeBartolo",
    streetSuffix: "Way",
    city: "Santa Clara",
    county: "Santa Clara",
    postalCode: "95054",
    latitude: 37.4030,
    longitude: -121.9697,
    extended: {
      building: "Levi's Stadium",
      floor: "2",
      room: "Press Box",
      placeType: "public",
      name: "San Francisco 49ers",
      landmark: "Levi's Stadium",
    },
  },
  {
    streetNumber: "525",
    streetName: "W Santa Clara",
    streetSuffix: "St",
    city: "San Jose",
    county: "Santa Clara",
    postalCode: "95113",
    latitude: 37.3328,
    longitude: -121.9011,
    extended: {
      building: "SAP Center",
      floor: "2",
      room: "Press Box",
      placeType: "public",
      name: "San Jose Sharks",
      landmark: "SAP Center",
    },
  },
  {
    streetNumber: "2800",
    streetName: "E Observatory",
    streetSuffix: "Rd",
    city: "Los Angeles",
    county: "Los Angeles",
    postalCode: "90027",
    latitude: 34.1184,
    longitude: -118.3004,
    extended: {
      building: "Griffith Observatory",
      floor: "3",
      room: "Planetarium",
      placeType: "public",
      name: "Griffith Observatory",
      landmark: "Griffith Park",
    },
  },
  {
    streetNumber: "6925",
    streetName: "Hollywood",
    streetSuffix: "Blvd",
    city: "Los Angeles",
    county: "Los Angeles",
    postalCode: "90028",
    latitude: 34.1022,
    longitude: -118.3409,
    extended: {
      building: "TCL Chinese Theatre",
      floor: "1",
      room: "Main",
      placeType: "public",
      name: "TCL Chinese Theatre",
      landmark: "Hollywood Walk of Fame",
    },
  },
  {
    streetNumber: "1200",
    streetName: "Getty Center",
    streetSuffix: "Dr",
    city: "Los Angeles",
    county: "Los Angeles",
    postalCode: "90049",
    latitude: 34.0780,
    longitude: -118.4741,
    extended: {
      building: "Getty Center",
      floor: "2",
      room: "South Pavilion",
      placeType: "public",
      name: "J. Paul Getty Museum",
      landmark: "Getty Center",
    },
  },
  {
    streetNumber: "111",
    streetName: "S Grand",
    streetSuffix: "Ave",
    city: "Los Angeles",
    county: "Los Angeles",
    postalCode: "90012",
    latitude: 34.0553,
    longitude: -118.2499,
    extended: {
      building: "Walt Disney Concert Hall",
      floor: "1",
      room: "Main Auditorium",
      placeType: "public",
      name: "LA Philharmonic",
      landmark: "Disney Hall",
    },
  },
  {
    streetNumber: "5905",
    streetName: "Wilshire",
    streetSuffix: "Blvd",
    city: "Los Angeles",
    county: "Los Angeles",
    postalCode: "90036",
    latitude: 34.0639,
    longitude: -118.3592,
    extended: {
      building: "LACMA Resnick Pavilion",
      floor: "1",
      room: "A",
      placeType: "public",
      name: "LACMA",
      landmark: "LACMA",
    },
  },
  {
    streetNumber: "340",
    streetName: "Royce",
    streetSuffix: "Dr",
    city: "Los Angeles",
    county: "Los Angeles",
    postalCode: "90095",
    latitude: 34.0729,
    longitude: -118.4427,
    extended: {
      building: "Royce Hall",
      floor: "1",
      room: "Auditorium",
      placeType: "public",
      name: "UCLA",
      landmark: "UCLA Campus",
    },
  },
  {
    streetNumber: "200",
    streetName: "Santa Monica",
    streetSuffix: "Pier",
    city: "Santa Monica",
    county: "Los Angeles",
    postalCode: "90401",
    latitude: 34.0098,
    longitude: -118.4974,
    extended: {
      building: "Pier Entrance",
      floor: "1",
      room: "Welcome Center",
      placeType: "public",
      name: "Santa Monica Pier",
      landmark: "Santa Monica Pier",
    },
  },
  {
    streetNumber: "910",
    streetName: "N Harbor",
    streetSuffix: "Dr",
    city: "San Diego",
    county: "San Diego",
    postalCode: "92101",
    latitude: 32.7137,
    longitude: -117.1751,
    extended: {
      building: "USS Midway",
      floor: "Hangar Deck",
      room: "Bridge",
      placeType: "public",
      name: "USS Midway Museum",
      landmark: "USS Midway",
    },
  },
  {
    streetNumber: "500",
    streetName: "Sea World",
    streetSuffix: "Dr",
    city: "San Diego",
    county: "San Diego",
    postalCode: "92109",
    latitude: 32.7641,
    longitude: -117.2270,
    extended: {
      building: "SeaWorld Visitor Center",
      floor: "1",
      room: "Lobby",
      placeType: "public",
      name: "SeaWorld San Diego",
      landmark: "SeaWorld",
    },
  },
  {
    streetNumber: "1500",
    streetName: "Orange",
    streetSuffix: "Ave",
    city: "Coronado",
    county: "San Diego",
    postalCode: "92118",
    latitude: 32.6809,
    longitude: -117.1773,
    extended: {
      building: "Hotel del Coronado Victorian Tower",
      floor: "3",
      room: "305",
      placeType: "hotel",
      name: "Hotel del Coronado",
      landmark: "Coronado Beach",
    },
  },
  {
    streetNumber: "1315",
    streetName: "10th",
    streetSuffix: "St",
    city: "Sacramento",
    county: "Sacramento",
    postalCode: "95814",
    latitude: 38.5766,
    longitude: -121.4934,
    extended: {
      building: "State Capitol",
      floor: "2",
      room: "Senate Chamber",
      placeType: "government",
      name: "California State Capitol",
      landmark: "State Capitol",
    },
  },
  {
    streetNumber: "9035",
    streetName: "Village",
    streetSuffix: "Dr",
    city: "Yosemite Valley",
    county: "Mariposa",
    postalCode: "95389",
    latitude: 37.7488,
    longitude: -119.5879,
    extended: {
      building: "Visitor Center",
      floor: "1",
      room: "Information Desk",
      placeType: "public",
      name: "Yosemite National Park",
      landmark: "Yosemite Valley",
    },
  },
  {
    streetNumber: "138",
    streetName: "Emerald Bay",
    streetSuffix: "Rd",
    city: "South Lake Tahoe",
    county: "El Dorado",
    postalCode: "96150",
    latitude: 38.9540,
    longitude: -120.0972,
    extended: {
      building: "Emerald Bay Visitor Center",
      floor: "1",
      room: "Front Desk",
      placeType: "public",
      name: "Emerald Bay State Park",
      landmark: "Emerald Bay",
    },
  },
  {
    streetNumber: "328",
    streetName: "Greenland",
    streetSuffix: "Blvd",
    city: "Furnace Creek",
    county: "Inyo",
    postalCode: "92328",
    latitude: 36.4615,
    longitude: -116.8675,
    extended: {
      building: "Death Valley Visitor Center",
      floor: "1",
      room: "Exhibits Hall",
      placeType: "public",
      name: "Death Valley National Park",
      landmark: "Furnace Creek",
    },
  },
  {
    streetNumber: "6554",
    streetName: "Park",
    streetSuffix: "Blvd",
    city: "Joshua Tree",
    county: "San Bernardino",
    postalCode: "92252",
    latitude: 34.1347,
    longitude: -116.3131,
    extended: {
      building: "Joshua Tree Visitor Center",
      floor: "1",
      room: "Welcome",
      placeType: "public",
      name: "Joshua Tree National Park",
      landmark: "Joshua Tree",
    },
  },
  {
    streetNumber: "47225",
    streetName: "Highway",
    streetSuffix: "1",
    city: "Big Sur",
    county: "Monterey",
    postalCode: "93920",
    latitude: 36.2470,
    longitude: -121.7920,
    extended: {
      building: "Park Entrance Station",
      floor: "1",
      room: "A",
      placeType: "public",
      name: "Pfeiffer Big Sur State Park",
      landmark: "Big Sur",
    },
  },
];
